model: 'default'
bert:
  batch_size: 1024
  seq_len: 20
  embed_size: 128
  inner_ff_size: 512
  n_heads: 8
  n_code: 8
  n_vocab: 40000
  dropout: 0.1
  n_workers: 12
  optim_kwargs: 
      lr: 0.0001
      weight_decay: 0.0001
      betas: 
        - .9
        - .999
  sentence_path : '/content/ERA1_S17_BERT_GPT_VIT/course_docs/BERT/training.txt'
  vocab_path : '/content/ERA1_S17_BERT_GPT_VIT/course_docs/BERT/vocab.txt'
  data_kwargs:
    shuffle:  true  
    drop_last: false 
    pin_memory: true 
    batch_size: 1024
  train_iter: 2000
  print_iter: 10
  embed_save_limit: 3000

