model: 'default'
bert:
  batch_size: 1024
  seq_len: 20
  embed_size: 128
  inner_ff_size: 512
  n_heads: 8
  n_code: 8
  n_vocab: 40000
  dropout: 0.1
  n_workers: 12
  optim_kwargs: 
      lr: 0.0001
      weight_decay: 0.0001
      betas: 
        - .9
        - .999
  sentence_path : '/content/ERA1_S17_BERT_GPT_VIT/course_docs/BERT/training.txt'
  vocab_path : '/content/ERA1_S17_BERT_GPT_VIT/course_docs/BERT/vocab.txt'
  data_kwargs:
    shuffle:  true  
    drop_last: false 
    pin_memory: true 
    batch_size: 1024
  train_iter: 2000
  print_iter: 10
  embed_save_limit: 3000

gpt:
  batch_size: 32
  block_size: 64
  dropout: 0.2
  lr: 0.0003
  num_embed: 768
  num_head: 6
  num_layer: 6
  max_iter: 1000
  eval_inter: 200
  data_path : '/content/ERA1_S17_BERT_GPT_VIT/course_docs/GPT/data/english.txt'
  inference_tokens: 50

vit:
  image_path: "/content/pizza_steak_sushi"
  batch_size: 32
  img_size: 224
  patch_size: 16
  num_transformer_layers: 12
  embedding_dim: 768
  mlp_size: 3072
  num_heads: 12
  attn_dropout: 0
  mlp_dropout: 0.1
  embedding_dropout: 0.1
  num_classes: 1000


